import { describe, it, expect } from 'vitest'
import * as yaml from 'yaml'
import { emitYaml } from '../src/emit.ts'
import type { Workflow, UsesStep } from '../src/types.ts'

const minimalWorkflow = (): Workflow => ({
  on: 'push',
  jobs: {
    build: {
      'runs-on': 'ubuntu-latest',
      steps: [{ run: 'echo hello' }],
    },
  },
})

describe('emitYaml', () => {
  it('emits the header comment as the first line', () => {
    const output = emitYaml(minimalWorkflow())
    expect(output.startsWith('# Generated by typed-gha. Do not edit by hand.\n')).toBe(true)
  })

  it('renders on: "push" as a scalar (not array)', () => {
    const output = emitYaml(minimalWorkflow())
    const parsed = yaml.parse(output.replace(/^#.*\n/, ''))
    expect(parsed.on).toBe('push')
  })

  it('renders on: [push, pull_request] as a YAML sequence', () => {
    const wf: Workflow = { ...minimalWorkflow(), on: ['push', 'pull_request'] }
    const output = emitYaml(wf)
    const parsed = yaml.parse(output.replace(/^#.*\n/, ''))
    expect(parsed.on).toEqual(['push', 'pull_request'])
  })

  it('renders on: { push: { branches: [main] } } as a nested mapping', () => {
    const wf: Workflow = { ...minimalWorkflow(), on: { push: { branches: ['main'] } } }
    const output = emitYaml(wf)
    const parsed = yaml.parse(output.replace(/^#.*\n/, ''))
    expect(parsed.on).toEqual({ push: { branches: ['main'] } })
  })

  it('renders on: { pull_request: {} } with an empty-mapping literal', () => {
    const wf: Workflow = { ...minimalWorkflow(), on: { pull_request: {} } }
    const output = emitYaml(wf)
    expect(output).toMatch(/pull_request: \{\}/)
  })

  it('renders permissions: "read-all" as a scalar string', () => {
    const wf: Workflow = { ...minimalWorkflow(), permissions: 'read-all' }
    const output = emitYaml(wf)
    const parsed = yaml.parse(output.replace(/^#.*\n/, ''))
    expect(parsed.permissions).toBe('read-all')
  })

  it('renders permissions object as a mapping', () => {
    const wf: Workflow = {
      ...minimalWorkflow(),
      permissions: { contents: 'read', 'pull-requests': 'write' },
    }
    const output = emitYaml(wf)
    const parsed = yaml.parse(output.replace(/^#.*\n/, ''))
    expect(parsed.permissions).toEqual({ contents: 'read', 'pull-requests': 'write' })
  })

  it('strips __outputs phantom field from UsesStep', () => {
    const step: UsesStep<string, string, Record<string, string>> = {
      uses: 'actions/checkout@v4',
      id: 'checkout',
      __outputs: { sha: '' },
    }
    const wf: Workflow = {
      on: 'push',
      jobs: { build: { 'runs-on': 'ubuntu-latest', steps: [step] } },
    }
    const output = emitYaml(wf)
    expect(output).not.toContain('__outputs')
  })

  it('omits keys with undefined values', () => {
    const wf: Workflow = {
      on: 'push',
      jobs: {
        build: {
          'runs-on': 'ubuntu-latest',
          name: undefined,
          steps: [{ run: 'echo hello' }],
        },
      },
    }
    const output = emitYaml(wf)
    expect(output).not.toContain('name:')
  })

  it('produces byte-identical output on repeated calls (determinism)', () => {
    const wf = minimalWorkflow()
    expect(emitYaml(wf)).toBe(emitYaml(wf))
  })

  it('renders boolean env value as unquoted YAML bool that round-trips to boolean', () => {
    const wf: Workflow = {
      on: 'push',
      jobs: {
        build: {
          'runs-on': 'ubuntu-latest',
          env: { CI: true },
          steps: [{ run: 'echo hello' }],
        },
      },
    }
    const output = emitYaml(wf)
    const parsed = yaml.parse(output.replace(/^#.*\n/, ''))
    expect(typeof parsed.jobs.build.env.CI).toBe('boolean')
    expect(parsed.jobs.build.env.CI).toBe(true)
  })

  it('preserves expression strings literally in run steps', () => {
    const wf: Workflow = {
      on: 'push',
      jobs: {
        build: {
          'runs-on': 'ubuntu-latest',
          steps: [{ run: '${{ github.event_name }}' }],
        },
      },
    }
    const output = emitYaml(wf)
    expect(output).toContain('${{ github.event_name }}')
  })
})
