import { stringify } from 'yaml'
import type { Workflow } from './types.ts'

const HEADER = '# Generated by typed-gha. Do not edit by hand.\n'

type Primitive = string | number | boolean | null
type JsonValue = Primitive | JsonValue[] | { [key: string]: JsonValue }

const clean = (value: unknown): JsonValue | undefined => {
  if (value === undefined) return undefined
  if (value === null || typeof value !== 'object') return value as Primitive
  if (Array.isArray(value)) {
    return (value as unknown[]).map(clean).filter((v): v is JsonValue => v !== undefined)
  }
  const result: { [key: string]: JsonValue } = {}
  for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
    // strip phantom type fields and undefined values
    if (k.startsWith('__')) continue
    const cleaned = clean(v)
    if (cleaned !== undefined) result[k] = cleaned
  }
  return result
}

export const emitYaml = (workflow: Workflow): string => {
  const cleaned = clean(workflow)
  return HEADER + stringify(cleaned, { lineWidth: 0, aliasDuplicateObjects: false })
}
