import { stringify } from 'yaml'
import type { Workflow } from './types.js'

const HEADER = '# Generated by typed-gha. Do not edit by hand.\n'

type Primitive = string | number | boolean | null
type JsonValue = Primitive | JsonValue[] | { [key: string]: JsonValue }

const clean = (value: unknown): JsonValue | undefined => {
  if (value === undefined) return undefined
  if (value === null || typeof value !== 'object') return value as Primitive
  if (Array.isArray(value)) {
    return (value as unknown[]).map(clean).filter((v): v is JsonValue => v !== undefined)
  }
  const result: { [key: string]: JsonValue } = {}
  for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
    // strip phantom type fields and undefined values
    if (k.startsWith('__')) continue
    const cleaned = clean(v)
    if (cleaned !== undefined) result[k] = cleaned
  }
  return result
}

/**
 * Serializes a `Workflow` definition to a YAML string ready to write to disk.
 *
 * @remarks
 * - **Deterministic output**: identical input always produces byte-identical output, making
 *   `--check` mode diffs reliable.
 * - **Phantom key stripping**: any object key whose name starts with `__` (e.g., `__outputs`
 *   on `UsesStep`) is removed before serialization — these keys exist for type inference only.
 * - **`undefined` vs `null`**: fields set to `undefined` are omitted entirely; fields set to
 *   `null` are preserved as YAML `null`. This matches GitHub Actions behavior for nullable fields.
 * - **Header comment**: the returned string is prefixed with
 *   `# Generated by typed-gha. Do not edit by hand.\n` so that committed YAML files carry a
 *   clear provenance notice.
 *
 * @param workflow - The workflow definition, typically the return value of `defineWorkflow`.
 * @returns The complete YAML document as a string, ready to write to `.github/workflows/*.yml`.
 * @example
 * ```ts
 * import { writeFileSync } from 'node:fs'
 * import { defineWorkflow, emitYaml } from '@typed-gha/core'
 *
 * const wf = defineWorkflow({ on: 'push', jobs: { build: { 'runs-on': 'ubuntu-latest', steps: [] } } })
 * writeFileSync('.github/workflows/ci.yml', emitYaml(wf))
 * ```
 */
export const emitYaml = (workflow: Workflow): string => {
  const cleaned = clean(workflow)
  return HEADER + stringify(cleaned, { lineWidth: 0, aliasDuplicateObjects: false })
}
