import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { mkdtemp, writeFile, readFile, rm, mkdir } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { runAdd } from '../src/add.js'

const FIXTURE = `
name: Setup Node
description: Set up a Node.js environment
inputs:
  node-version:
    description: Version Spec of the version to use
  lfs:
    description: Whether to download Git-LFS files
    default: false
  fetch-depth:
    description: Number of commits to fetch
    default: 1
outputs:
  node-version:
    description: The installed node version
  cache-hit:
    description: Whether there was a cache hit
runs:
  using: node20
  main: index.js
`

describe('runAdd', () => {
  let tmp: string
  let outDir: string
  let actionDir: string

  beforeEach(async () => {
    tmp = await mkdtemp(join(tmpdir(), 'typed-gha-add-'))
    outDir = join(tmp, 'out')
    actionDir = join(tmp, 'setup-node')
    await mkdir(actionDir)
    await writeFile(join(actionDir, 'action.yml'), FIXTURE)
  })

  afterEach(async () => {
    await rm(tmp, { recursive: true, force: true })
  })

  it('generates a wrapper file from a local action.yml', async () => {
    const result = await runAdd({ ref: actionDir, dir: outDir })
    expect(result.outputPath).toMatch(/setup-node\.ts$/)
    const content = await readFile(result.outputPath, 'utf8')
    expect(content).toContain('// Generated by typed-gha from')
    expect(content).toContain("'node-version'?: string")
    expect(content).toContain('lfs?: boolean | string')
    expect(content).toContain("'fetch-depth'?: number | string")
    expect(content).toContain("'cache-hit': string")
    expect(content).toContain('export const setupNode = makeAction<')
  })

  it('overwrites existing file idempotently', async () => {
    await runAdd({ ref: actionDir, dir: outDir })
    const first = await readFile(join(outDir, 'setup-node.ts'), 'utf8')
    await runAdd({ ref: actionDir, dir: outDir })
    const second = await readFile(join(outDir, 'setup-node.ts'), 'utf8')
    expect(first).toBe(second)
  })

  it('respects --dir option', async () => {
    const customDir = join(tmp, 'custom')
    const result = await runAdd({ ref: actionDir, dir: customDir })
    expect(result.outputPath).toContain('custom/')
  })

  it('uses action dir name for the output file', async () => {
    const result = await runAdd({ ref: actionDir, dir: outDir })
    expect(result.outputPath).toMatch(/setup-node\.ts$/)
  })
})
