import { describe, it, expect, afterEach } from 'vitest'
import { mkdtemp, mkdir, writeFile, readFile, rm, stat } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { tmpdir } from 'node:os'
import { parse } from 'yaml'
import { runBuild } from '../src/build.js'

// Absolute path to @typed-gha/core so fixture TS files can import it from a tmp dir
const CORE_INDEX = resolve(new URL('../../../packages/core/src/index.ts', import.meta.url).pathname)

const WORKFLOW_FIXTURE = `import { defineWorkflow } from '${CORE_INDEX}'
export default defineWorkflow({
  on: { push: {} },
  jobs: {
    ci: {
      'runs-on': 'ubuntu-latest',
      steps: [{ uses: 'actions/checkout@v4' }],
    },
  },
})
`

const BAD_FIXTURE = `export const x = {}`

// Non-object default exports — each should be rejected by the typeof !== 'object' guard in loadWorkflow
const FUNCTION_EXPORT_FIXTURE = `export default () => ({ on: 'push', jobs: {} })`
const NULL_EXPORT_FIXTURE = `export default null`
const NUMBER_EXPORT_FIXTURE = `export default 42`
const STRING_EXPORT_FIXTURE = `export default 'hello'`

describe('runBuild', () => {
  let tmp = ''

  afterEach(async () => {
    if (tmp) await rm(tmp, { recursive: true, force: true })
  })

  const makeWorkflowFile = async (name: string, content = WORKFLOW_FIXTURE): Promise<string> => {
    const wfDir = join(tmp, '.github', 'workflows')
    await mkdir(wfDir, { recursive: true })
    const file = join(wfDir, name)
    await writeFile(file, content)
    return file
  }

  it('happy path: write mode writes yml file', async () => {
    tmp = await mkdtemp(join(tmpdir(), 'typed-gha-build-'))
    await makeWorkflowFile('ci.workflow.ts')

    const result = await runBuild({ cwd: tmp, check: false })

    expect(result.written).toHaveLength(1)
    expect(result.drift).toHaveLength(0)

    const outPath = join(tmp, '.github', 'workflows', 'ci.yml')
    const content = await readFile(outPath, 'utf8')
    expect(content.startsWith('# Generated by typed-gha. Do not edit by hand.')).toBe(true)

    const parsed = parse(content)
    expect(parsed).toHaveProperty('on')
    expect(parsed).toHaveProperty('jobs')
    expect(parsed.jobs.ci['runs-on']).toBe('ubuntu-latest')
  })

  it('throws for missing default export', async () => {
    tmp = await mkdtemp(join(tmpdir(), 'typed-gha-build-'))
    await makeWorkflowFile('bad.workflow.ts', BAD_FIXTURE)

    await expect(runBuild({ cwd: tmp, check: false })).rejects.toThrow(/bad\.workflow\.ts/)
    await expect(runBuild({ cwd: tmp, check: false })).rejects.toThrow(/default export/)
  })

  it('check mode reports no drift when file is up to date', async () => {
    tmp = await mkdtemp(join(tmpdir(), 'typed-gha-build-'))
    await makeWorkflowFile('ci.workflow.ts')

    // Write first
    await runBuild({ cwd: tmp, check: false })

    // Then check
    const result = await runBuild({ cwd: tmp, check: true })
    expect(result.drift).toHaveLength(0)
    expect(result.written).toHaveLength(0)
  })

  it('check mode detects drift when file has been modified', async () => {
    tmp = await mkdtemp(join(tmpdir(), 'typed-gha-build-'))
    await makeWorkflowFile('ci.workflow.ts')

    await runBuild({ cwd: tmp, check: false })

    const outPath = join(tmp, '.github', 'workflows', 'ci.yml')
    // Append garbage to corrupt the output
    await writeFile(outPath, (await readFile(outPath, 'utf8')) + '\n# garbage\n')

    const result = await runBuild({ cwd: tmp, check: true })
    expect(result.drift).toHaveLength(1)
    expect(result.drift[0]).toBe(outPath)
  })

  // --- Non-object default export tests ---
  // The guard at build.ts line ~43: `typeof value !== 'object'` rejects function/null/number/string.

  it('throws when default export is a function', async () => {
    tmp = await mkdtemp(join(tmpdir(), 'typed-gha-build-'))
    await makeWorkflowFile('fn.workflow.ts', FUNCTION_EXPORT_FIXTURE)

    // A function passes typeof check (`typeof fn === 'function'`, not 'object'), so it should throw.
    await expect(runBuild({ cwd: tmp, check: false })).rejects.toThrow(/fn\.workflow\.ts/)
    await expect(runBuild({ cwd: tmp, check: false })).rejects.toThrow(/missing default export/)
  })

  it('throws when default export is null', async () => {
    tmp = await mkdtemp(join(tmpdir(), 'typed-gha-build-'))
    await makeWorkflowFile('null.workflow.ts', NULL_EXPORT_FIXTURE)

    // null satisfies `typeof null === 'object'` but fails the `value === null` check first.
    await expect(runBuild({ cwd: tmp, check: false })).rejects.toThrow(/null\.workflow\.ts/)
    await expect(runBuild({ cwd: tmp, check: false })).rejects.toThrow(/missing default export/)
  })

  it('throws when default export is a number', async () => {
    tmp = await mkdtemp(join(tmpdir(), 'typed-gha-build-'))
    await makeWorkflowFile('num.workflow.ts', NUMBER_EXPORT_FIXTURE)

    await expect(runBuild({ cwd: tmp, check: false })).rejects.toThrow(/num\.workflow\.ts/)
    await expect(runBuild({ cwd: tmp, check: false })).rejects.toThrow(/missing default export/)
  })

  it('throws when default export is a string', async () => {
    tmp = await mkdtemp(join(tmpdir(), 'typed-gha-build-'))
    await makeWorkflowFile('str.workflow.ts', STRING_EXPORT_FIXTURE)

    await expect(runBuild({ cwd: tmp, check: false })).rejects.toThrow(/str\.workflow\.ts/)
    await expect(runBuild({ cwd: tmp, check: false })).rejects.toThrow(/missing default export/)
  })

  it('check mode with two workflows only flags the drifted one', async () => {
    tmp = await mkdtemp(join(tmpdir(), 'typed-gha-build-'))
    await makeWorkflowFile('a.workflow.ts')
    await makeWorkflowFile('b.workflow.ts')

    await runBuild({ cwd: tmp, check: false })

    const bOut = join(tmp, '.github', 'workflows', 'b.yml')
    await writeFile(bOut, (await readFile(bOut, 'utf8')) + '\n# garbage\n')

    const result = await runBuild({ cwd: tmp, check: true })
    expect(result.drift).toHaveLength(1)
    expect(result.drift[0]).toBe(bOut)
  })
})
