import { describe, it, expect } from 'vitest'
import { generateWrapper } from '../src/generate.js'
import type { ActionSource } from '../src/resolve.js'
import type { ParsedAction } from '../src/parse.js'

const makeSource = (ref: string, repoUrl: string | null = null): ActionSource => ({
  raw: '',
  ref,
  repoUrl,
})

const minimalAction: ParsedAction = {
  name: 'Setup Node',
  description: 'Set up a specific version of Node.js',
  inputs: [],
  outputs: [],
  runsUsing: 'node20',
}

const fullAction: ParsedAction = {
  name: 'Checkout',
  description: 'Check out a Git repository',
  inputs: [
    {
      key: 'lfs',
      description: 'Whether to download Git-LFS files',
      required: false,
      default: false,
      inferredType: 'boolean | string',
    },
    {
      key: 'fetch-depth',
      description: 'Number of commits to fetch',
      required: false,
      default: 1,
      inferredType: 'number | string',
    },
    {
      key: 'token',
      description: 'Personal access token',
      required: false,
      default: '${{ github.token }}',
      inferredType: 'string',
    },
  ],
  outputs: [
    { key: 'ref', description: 'The branch, tag or SHA that was checked out' },
    { key: 'commit', description: 'The commit SHA that was checked out' },
  ],
  runsUsing: 'node20',
}

describe('generateWrapper', () => {
  it('includes header comment with source ref', () => {
    const result = generateWrapper(minimalAction, makeSource('actions/setup-node@v4'))
    expect(result).toContain('// Generated by typed-gha from actions/setup-node@v4. Do not edit by hand.')
  })

  it('imports makeAction from @typed-gha/core/actions/_factory', () => {
    const result = generateWrapper(minimalAction, makeSource('actions/setup-node@v4'))
    expect(result).toContain("import { makeAction } from '@typed-gha/core/actions/_factory'")
  })

  it('generates camelCase function name from ref (setup-node → setupNode)', () => {
    const result = generateWrapper(minimalAction, makeSource('actions/setup-node@v4'))
    expect(result).toContain('export const setupNode =')
  })

  it('generates PascalCase type names from ref', () => {
    const result = generateWrapper(minimalAction, makeSource('actions/setup-node@v4'))
    expect(result).toContain('export type SetupNodeInputs =')
    expect(result).toContain('export type SetupNodeOutputs =')
  })

  it('derives names from single-segment ref (checkout)', () => {
    const result = generateWrapper(
      { ...minimalAction, name: 'Checkout' },
      makeSource('actions/checkout@v4'),
    )
    expect(result).toContain('export const checkout =')
    expect(result).toContain('export type CheckoutInputs =')
    expect(result).toContain('export type CheckoutOutputs =')
  })

  it('renders boolean | string type for boolean-default inputs', () => {
    const result = generateWrapper(fullAction, makeSource('actions/checkout@v4'))
    expect(result).toContain('lfs?: boolean | string')
  })

  it('renders number | string type for numeric-default inputs', () => {
    const result = generateWrapper(fullAction, makeSource('actions/checkout@v4'))
    expect(result).toContain("'fetch-depth'?: number | string")
  })

  it('adds @defaultValue tag when default exists', () => {
    const result = generateWrapper(fullAction, makeSource('actions/checkout@v4'))
    expect(result).toContain('@defaultValue false')
    expect(result).toContain('@defaultValue 1')
    expect(result).toContain('@defaultValue ${{ github.token }}')
  })

  it('adds @see link when repoUrl is provided', () => {
    const result = generateWrapper(
      minimalAction,
      makeSource('actions/setup-node@v4', 'https://github.com/actions/setup-node'),
    )
    expect(result).toContain('@see https://github.com/actions/setup-node')
  })

  it('omits @see when repoUrl is null', () => {
    const result = generateWrapper(minimalAction, makeSource('actions/setup-node@v4', null))
    expect(result).not.toContain('@see')
  })

  it('renders outputs with string type', () => {
    const result = generateWrapper(fullAction, makeSource('actions/checkout@v4'))
    expect(result).toContain("ref: string")
    expect(result).toContain("commit: string")
  })

  it('uses Record<string, never> for empty outputs', () => {
    const result = generateWrapper(minimalAction, makeSource('actions/setup-node@v4'))
    expect(result).toContain('export type SetupNodeOutputs = Record<string, never>')
  })

  it('passes ref through to makeAction generic and call args', () => {
    const result = generateWrapper(minimalAction, makeSource('actions/setup-node@v4'))
    expect(result).toContain("makeAction<'actions/setup-node@v4', SetupNodeInputs, SetupNodeOutputs>('actions/setup-node@v4')")
  })
})

describe('generateWrapper — reserved keyword handling', () => {
  it('appends underscore to function name when camelCase form is a reserved word', () => {
    const action: ParsedAction = {
      name: 'Class', description: 'desc',
      inputs: [], outputs: [], runsUsing: 'node20',
    }
    const result = generateWrapper(action, makeSource('owner/class@v1'))
    expect(result).toContain('export const class_ = makeAction<')
    expect(result).not.toContain('export const class =')
  })

  it('appends underscore for delete, new, default, etc.', () => {
    for (const name of ['delete', 'new', 'default', 'function', 'return']) {
      const action: ParsedAction = {
        name, description: '', inputs: [], outputs: [], runsUsing: 'node20',
      }
      const result = generateWrapper(action, makeSource(`owner/${name}@v1`))
      expect(result).toContain(`export const ${name}_ = makeAction<`)
    }
  })

  it('quotes input keys that are reserved words', () => {
    const action: ParsedAction = {
      name: 'Test', description: '',
      inputs: [{ key: 'class', description: 'A class', required: false, inferredType: 'string' }],
      outputs: [], runsUsing: 'node20',
    }
    const result = generateWrapper(action, makeSource('owner/test@v1'))
    expect(result).toContain("'class'?: string")
    expect(result).not.toMatch(/^\s*class\?: string/m)
  })

  it('quotes output keys that are reserved words', () => {
    const action: ParsedAction = {
      name: 'Test', description: '',
      inputs: [],
      outputs: [{ key: 'return', description: 'The return value' }],
      runsUsing: 'node20',
    }
    const result = generateWrapper(action, makeSource('owner/test@v1'))
    expect(result).toContain("'return': string")
    expect(result).not.toMatch(/^\s*return: string/m)
  })

  it('does not affect non-reserved names', () => {
    const action: ParsedAction = {
      name: 'Setup Node', description: '',
      inputs: [], outputs: [], runsUsing: 'node20',
    }
    const result = generateWrapper(action, makeSource('actions/setup-node@v4'))
    expect(result).toContain('export const setupNode = makeAction<')
    expect(result).not.toContain('setupNode_')
  })
})
