import type { ParsedAction, ParsedInput, ParsedOutput } from './parse.js'
import type { ActionSource } from './resolve.js'

// Extract the action name segment from a ref like 'actions/setup-node@v4' → 'setup-node'
const extractBaseName = (ref: string): string => {
  // Remove version suffix (e.g. @v4)
  const withoutVersion = ref.split('@')[0] ?? ref
  // Take the last path segment
  const segments = withoutVersion.split('/')
  return segments[segments.length - 1] ?? withoutVersion
}

// 'setup-node' → 'setupNode', 'checkout' → 'checkout', 'configure-aws-credentials' → 'configureAwsCredentials'
const toCamelCase = (name: string): string =>
  name
    .split('-')
    .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('')

// 'setup-node' → 'SetupNode'
const toPascalCase = (name: string): string => {
  const camel = toCamelCase(name)
  return camel.charAt(0).toUpperCase() + camel.slice(1)
}

// Returns true if the key is a valid JS identifier (no quoting needed)
const isValidIdentifier = (key: string): boolean => /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key)

const renderInputField = (input: ParsedInput): string => {
  const keyStr = isValidIdentifier(input.key) ? input.key : `'${input.key}'`
  const lines: string[] = []
  lines.push(`  /** ${input.description}`)
  if (input.default !== undefined) {
    lines.push(`   * @defaultValue ${input.default}`)
  }
  lines.push('   */')
  lines.push(`  ${keyStr}?: ${input.inferredType}`)
  return lines.join('\n')
}

const renderOutputField = (output: ParsedOutput): string => {
  const keyStr = isValidIdentifier(output.key) ? output.key : `'${output.key}'`
  const lines: string[] = []
  lines.push(`  /** ${output.description} */`)
  lines.push(`  ${keyStr}: string`)
  return lines.join('\n')
}

export const generateWrapper = (parsed: ParsedAction, source: ActionSource): string => {
  const baseName = extractBaseName(source.ref)
  const camelName = toCamelCase(baseName)
  const pascalName = toPascalCase(baseName)

  const inputsTypeName = `${pascalName}Inputs`
  const outputsTypeName = `${pascalName}Outputs`

  const lines: string[] = []

  // Header
  lines.push(`// Generated by typed-gha from ${source.ref}. Do not edit by hand.`)
  lines.push('')

  // Import
  lines.push(`import { makeAction } from '@typed-gha/core/actions/_factory'`)
  lines.push('')

  // TSDoc block
  lines.push('/**')
  lines.push(` * ${parsed.name}`)
  lines.push(` *`)
  lines.push(` * ${parsed.description}`)
  if (source.repoUrl !== null) {
    lines.push(` * @see ${source.repoUrl}`)
  }
  lines.push(' */')

  // Inputs type
  if (parsed.inputs.length === 0) {
    lines.push(`export type ${inputsTypeName} = Record<string, never>`)
  } else {
    lines.push(`export type ${inputsTypeName} = {`)
    for (const input of parsed.inputs) {
      lines.push(renderInputField(input))
    }
    lines.push('}')
  }
  lines.push('')

  // Outputs type
  if (parsed.outputs.length === 0) {
    lines.push(`export type ${outputsTypeName} = Record<string, never>`)
  } else {
    lines.push(`export type ${outputsTypeName} = {`)
    for (const output of parsed.outputs) {
      lines.push(renderOutputField(output))
    }
    lines.push('}')
  }
  lines.push('')

  // Export const
  lines.push(
    `export const ${camelName} = makeAction<'${source.ref}', ${inputsTypeName}, ${outputsTypeName}>('${source.ref}')`,
  )
  lines.push('')

  return lines.join('\n')
}
